### ISSUE TITLE
Undo/Restore placeholder list

### ISSUE THREAD

**Issue by codewzrd** [igorlogius/open-with-selection#1]
**Is your feature request related to a problem? Please describe.**
As a user, if I delete a placeholder, I would like the ability to undo the delete. I would also like the ability to restore the list back to the default list provided when the addon was installed.

**Describe the solution you'd like**
Provide two buttons.
1. Undo
2. Restore

**Comment by igorlogius** [comment]
`Undo` seems kind of pointless, since a user is already forced to confirm their delete and modification actions by clicking the `Save Changes` button, but a restore function seems reaonable.
